name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggers

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17' # Update to Java 17

    - name: Grant execute permission for Gradlew
      run: chmod +x ./gradlew

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '7.4' # Use a compatible Gradle version

    - name: Build with Gradle
      run: ./gradlew assembleDebug --warning-mode all  # Enable warning mode to highlight deprecated features and generate APK file

    - name: Run tests
      run: ./gradlew test

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4 # Update to the latest version
      with:
        name: build-artifacts
        path: app/build/outputs/apk/debug/  # Specify the correct path for the APK file

    - name: Push APK to GitHub
      run: |
        git config --global user.email "chinmay.malvania@gmail.com"
        git config --global user.name "chinmaym505"
        git checkout master
        mkdir -p apk-output
        cp app/build/outputs/apk/debug/app-debug.apk apk-output/
        git add apk-output/app-debug.apk
        git commit -m "{AUTOMATION} Add generated APK"
        git push origin master --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
