name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggers

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Grant execute permission for Gradlew
      run: chmod +x ./gradlew

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '7.4' # Use a compatible Gradle version

    - name: Build with Gradle
      run: ./gradlew build --warning-mode all  # Enable warning mode to highlight deprecated features

    - name: Run tests
      run: ./gradlew test

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4 # Update to the latest version
      with:
        name: build-artifacts
        path: app/build/outputs/
